src/objects/Campaign_List_Generation__c.object
<CustomObject>
    <label>Campaign List Generation</label>
    <nameField>
        <displayFormat>CL-{000000}</displayFormat>
        <label>Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Campaign List Generation</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Campaign_List_Generation_Criteria__c.object
<CustomObject>
    <fields>
        <fullName>Campaign_List_Generation__c</fullName>
        <label>Campaign List Generation</label>
        <referenceTo>Campaign_List_Generation__c</referenceTo>
        <relationshipLabel>Campaign List Generation Criteria</relationshipLabel>
        <relationshipName>Campaign_List_Generation_Criteria</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Field_API_Name__c</fullName>
        <label>Field API Name</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Field_Label__c</fullName>
        <label>Field</label>
        <length>150</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Field_Type__c</fullName>
        <label>Field Type</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Object__c</fullName>
        <label>Object</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Operator__c</fullName>
        <label>Operator</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Campaign List Generation Criteria</label>
    <nameField>
        <displayFormat>CR-{000000}</displayFormat>
        <label>Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Campaign List Generation Criteria</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ctlrCampaignListCopy.cls
public with sharing class ctlrCampaignListCopy {
	string listId = '';
	Campaign_List_Generation__c obj;
	public ctlrCampaignListCopy(apexpages.standardController con){
		obj = (Campaign_List_Generation__c) con.getrecord();
	}
	
	public pagereference copy(){
		Campaign_List_Generation__c newObj = obj.clone();
		insert newObj;
		list<Campaign_List_Generation_Criteria__c> clist = [Select c.Value__c, 
																	c.Operator__c, 
																	c.Object__c, 
																	c.Id, 
																	c.Field_Type__c, 
																	c.Field_Label__c, 
																	c.Field_API_Name__c 
															From Campaign_List_Generation_Criteria__c c
															Where c.Campaign_List_Generation__c = : obj.Id];
		
		list<Campaign_List_Generation_Criteria__c> newclist = new list<Campaign_List_Generation_Criteria__c>();
		
		for (Campaign_List_Generation_Criteria__c c : clist){
			Campaign_List_Generation_Criteria__c newC = new Campaign_List_Generation_Criteria__c();
			newc.Value__c = c.Value__c;
			newc.Operator__c = c.Operator__c;
			newc.Object__c = c.Object__c;
			newc.Field_Type__c = c.Field_Type__c;
			newc.Field_Label__c = c.Field_Label__c;
			newc.Field_API_Name__c = c.Field_API_Name__c;
			newc.Campaign_List_Generation__c = newObj.id;
			newclist.add (newc);
		}
		insert(newclist);
		return new pagereference('/' + newObj.Id);
		
	}
	
}