src/objects/Campaign_List_Additional_Campaigns__c.object
<CustomObject>
    <fields>
        <fullName>Campaign_List_Generation__c</fullName>
        <label>Campaign List Generation</label>
        <referenceTo>Campaign_List_Generation__c</referenceTo>
        <relationshipLabel>Additional Campaigns</relationshipLabel>
        <relationshipName>Additional_Campaigns</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Campaign__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Campaign</label>
        <referenceTo>Campaign</referenceTo>
        <relationshipLabel>Additional Campaigns</relationshipLabel>
        <relationshipName>Additional_Campaigns</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Percentage__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Split Percentage</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Campaign List -  Additional Campaigns</label>
    <nameField>
        <displayFormat>AC-{00000000}</displayFormat>
        <label>Campaign List -  Additional Campaigns Na</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Additional Campaigns</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Campaign_List_Generation__c.object
<CustomObject>
    <fields>
        <fullName>Campaign__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Campaign</label>
        <referenceTo>Campaign</referenceTo>
        <relationshipLabel>Campaign List Generation</relationshipLabel>
        <relationshipName>Campaign_List_Generation</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Members_Selected__c</fullName>
        <label>Members Selected</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Memebers_Added__c</fullName>
        <label>Members Added</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Percentage__c</fullName>
        <defaultValue>100</defaultValue>
        <inlineHelpText>If record distribution = &quot;Percentage&quot; then us this field to determine the percentage of records that are allocated to the primary campaign.</inlineHelpText>
        <label>Percentage</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Record_Distribution__c</fullName>
        <inlineHelpText>Determines how members are added to multiple campaigns. Automatic = evenly distributed, percentage uses the percentage value to determine distribution.</inlineHelpText>
        <label>Record Distribution</label>
        <picklist>
            <picklistValues>
                <fullName>Automatic</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Use Percentage</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In-Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Complete</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Transaction_Fields__c</fullName>
        <label>Transaction Fields</label>
        <summaryFilterItems>
            <field>Campaign_List_Generation_Criteria__c.Object__c</field>
            <operation>equals</operation>
            <value>Transaction</value>
        </summaryFilterItems>
        <summaryForeignKey>Campaign_List_Generation_Criteria__c.Campaign_List_Generation__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>Campaign List Generation</label>
    <nameField>
        <displayFormat>CL-{000000}</displayFormat>
        <label>Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Campaign List Generation</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/CLG_App_Settings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>CLG App Settings</label>
</CustomObject>

src/classes/clsCampaignListGenerator.cls
global class clsCampaignListGenerator implements Database.Batchable<sObject>, Database.stateful{
	
	public boolean isTest = false;
	public string listId {get;set;}
	private string campaignId = '';
	private integer membersAdded = 0;
	private integer membersSelected = 0;
	private boolean hasTransactionFieldsInQuery = false;
	
	private Map<Id, Integer> campaignsMap = new Map<Id, Integer>();
	private List<String> campaignsList = new List<String>();
	private boolean useAutoDistribution = true; 
	private string soql = '';
	private string subQuerySoql = '';
	private integer campaignIndex = 0;
	private integer campaignRecordCount = 0;
	
	global  database.querylocator start(Database.BatchableContext bc){
		Campaign_List_Generation__c clist = [select id,Transaction_Fields__c, Record_Distribution__c, Percentage__c, campaign__c from Campaign_List_Generation__c where id = : listId];
		campaignId = clist.Campaign__c;
		List<Campaign_List_Additional_Campaigns__c> adCamp = [select Id, Campaign__c, Percentage__c from Campaign_List_Additional_Campaigns__c where Campaign_List_Generation__c = : listId];
		campaignsMap.put(campaignId, (integer.valueof(clist.percentage__c / 10)));
		campaignsList.add(campaignId);
		if(clist.Record_Distribution__c != 'Automatic'){
			useAutoDistribution = false;
		}
		for (Campaign_List_Additional_Campaigns__c c : adCamp){
			campaignsMap.put(c.campaign__c, (integer.valueof(c.percentage__c / 10)));
			campaignsList.add(c.campaign__c);
		}		
		
		//if (clist.Transaction_Fields__c > 0){
		//	hasTransactionFieldsInQuery = true;
		//	subQuerySoql = 'select account__r.id, account__r.personContactId from Sales_Data_Transaction_Detail__c where Account__c in ({SCOPE}) and account__r.personemail != null and account__r.personHasOptedOutOfEmail = false and account__r.Email_Indicator__pc != \'Hard Bounce\' and ';
		//}else{
			subQuerySoql = 'select id from contact where id in ({SCOPE}) and email != null and ' ;	
		//} 
		subQuerySoql = subQuerySoql + clsCampaignListSOQLGenerator.whereClause(listId);
		
		list<CLG_App_Settings__c> whereClause = [select id, value__c from CLG_App_Settings__c where name like 'CampaignList_SOQL_%'];
		if (whereClause.size() > 0){
			soql = 'select id from contact where ' ;
			for (CLG_App_Settings__c clause : whereClause){
				soql = soql + clause.value__c + ' and ';
			}
			soql = soql.substring(0,soql.length()-5);
		}else{
			soql = 'select id from contact' ;	
		}
		
		 
		
		if (isTest){
			soql = 'select id from contact limit 20'; 
		}
		return Database.getQueryLocator(soql); 
	}
	
	global void execute(Database.BatchableContext bc, sObject[] objects){
		
		string scopeId = '';
		for (sObject so : objects){
			scopeId = scopeId + '\'' + so.id + '\',';
		}
		scopeId = scopeId.substring(0, scopeId.length()-1);
		string batchSOQL = subQuerySoql.replace('{SCOPE}', scopeId);
		
		system.debug('\n\n SOQL: ' + SOQL);
		system.debug('\n\n batchSOQL: ' + batchSOQL);
		List<sObject> qso = Database.query(batchSOQL);
		
		List<CampaignMember> cm = new List<CampaignMember>();
		//integer currentIndex = 0;
		//integer currentRecordCount = 0;
		system.debug('\n\n' + soql);
		for (string s : campaignsList){
			system.debug('\n\n' + s + ' : ' + campaignsMap.get(s));
		}
		if(useAutoDistribution){
			for (sobject so : qso){
				membersSelected ++;
				string personContactId = '';
				if (hasTransactionFieldsInQuery){
					//Sales_Data_Transaction_Detail__c t = (Sales_Data_Transaction_Detail__c) so;
					//personContactId = t.account__r.personContactId;
				}else{
					Contact c = (Contact) so;
					personContactId = c.id;
				}
				CampaignMember m = new CampaignMember();
				m.CampaignId = campaignsList[campaignIndex];
				campaignIndex ++;
				if(campaignIndex > (campaignsList.size() - 1) ){
					campaignIndex = 0;
				}
				m.ContactId = personContactId;
				cm.add(m);
			}
		}else{	
			for (sobject so : qso){
				membersSelected ++;
				string personContactId = '';
				if (hasTransactionFieldsInQuery){
					//Sales_Data_Transaction_Detail__c t = (Sales_Data_Transaction_Detail__c) so;
					//personContactId = t.account__r.personContactId;
				}else{
					Contact c = (Contact) so;
					personContactId = c.id;
				}
				CampaignMember m = new CampaignMember();
				
				string camId = '';
				while(camId==''){
					integer percent =  campaignsMap.get(campaignsList[campaignIndex]);
					if (percent > 0 && campaignRecordCount < percent){
						camId = campaignsList[campaignIndex];
						campaignRecordCount++;
					}else{
						campaignIndex ++;
						campaignRecordCount = 0;
						if(campaignIndex > (campaignsList.size()-1) ){
							campaignIndex = 0;
						}						
					}
				}
				m.CampaignId = camid;
				m.ContactId = personContactId;
				cm.add(m);
			}
		}
		
		Database.Saveresult[] dsr = database.insert(cm, false);
		for(Database.Saveresult sr : dsr){
			if (sr.isSuccess()){
				membersAdded ++;
			}
		}
		Campaign_List_Generation__c clg = [select Id, Status__c, Memebers_Added__c, Members_Selected__c from Campaign_List_Generation__c where id = : listId];
		clg.Memebers_Added__c = membersAdded;
		clg.Members_Selected__c = membersSelected;
		clg.Status__c = 'In Progress';
		update(clg);
	}
		
	global void finish(Database.BatchableContext bc){
		/*Campaign_List_Generation__c clg = [select Id, createdbyid, Status__c, Memebers_Added__c, Members_Selected__c from Campaign_List_Generation__c where id = : listId];
		clg.Memebers_Added__c = membersAdded;
		clg.Members_Selected__c = membersSelected;
		clg.Status__c = 'Completed';
		update(clg);
		User u = [select FirstName, email from user where id = : clg.createdbyid];
       	List<string> toAddresses = new List<string>();
       	toAddresses.add(u.email);
        Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
		mail.setToAddresses(toAddresses);
		mail.setSenderDisplayName('Campaign List Generator');
		mail.setSubject('List generation completed');
		mail.setPlainTextBody('Hi ' + u.FirstName + ', your list has been generated. '+ membersSelected + ' selected and ' + membersAdded + ' members added.');
		Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });*/
	}
}