src/objects/Campaign_List_Generation__c.object
<CustomObject>
    <fields>
        <fullName>Campaign__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Campaign</label>
        <referenceTo>Campaign</referenceTo>
        <relationshipLabel>Campaign List Generation</relationshipLabel>
        <relationshipName>Campaign_List_Generation</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Transaction_Fields__c</fullName>
        <label>Transaction Fields</label>
        <summaryFilterItems>
            <field>Campaign_List_Generation_Criteria__c.Object__c</field>
            <operation>equals</operation>
            <value>Transaction</value>
        </summaryFilterItems>
        <summaryForeignKey>Campaign_List_Generation_Criteria__c.Campaign_List_Generation__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>Campaign List Generation</label>
    <nameField>
        <displayFormat>CL-{000000}</displayFormat>
        <label>Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Campaign List Generation</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Campaign_List_Generation_Criteria__c.object
<CustomObject>
    <fields>
        <fullName>Calculated_Field_Type__c</fullName>
        <formula>CASE(  LOWER(Field_Type__c) , 
&apos;combobox&apos;, &apos;STRING&apos;, 
&apos;datacategorygroupreference&apos;, &apos;STRING&apos;, 
&apos;email&apos;, &apos;STRING&apos;, 
&apos;encryptedstring&apos;, &apos;STRING&apos;, 
&apos;id&apos;, &apos;STRING&apos;, 
&apos;multipicklist&apos;, &apos;STRING&apos;, 
&apos;phone&apos;, &apos;STRING&apos;, 
&apos;picklist&apos;, &apos;STRING&apos;, 
&apos;reference&apos;, &apos;STRING&apos;, 
&apos;string&apos;, &apos;STRING&apos;, 
&apos;textarea&apos;, &apos;STRING&apos;, 
&apos;url&apos;, &apos;STRING&apos;, 

&apos;date&apos;, &apos;DATE&apos;, 
&apos;datetime&apos;, &apos;DATETIME&apos;, 

&apos;percent&apos;, &apos;NUMBER&apos;, 
&apos;integer&apos;, &apos;NUMBER&apos;, 
&apos;double&apos;, &apos;NUMBER&apos;, 
&apos;currency&apos;, &apos;NUMBER&apos;, 

&apos;boolean&apos;, &apos;BOOLEAN&apos;, 
&apos;ERROR&apos;
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Calculated Field Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Calculated_Operator__c</fullName>
        <formula>CASE ( Operator__c , 
&apos;Equals&apos;, &apos; = &apos;,
&apos;Contains&apos;, &apos; Like &apos;,
&apos;Does Not Contain&apos;, &apos;LIKE&apos;,
&apos;Starts With&apos;, &apos; Like &apos;,
&apos;Not Equal&apos;, &apos; != &apos;,
&apos;Less Than&apos;, &apos; &lt; &apos;,
&apos;Greater Than&apos;, &apos; &gt; &apos;,
&apos;In Range&apos;, &apos; In &apos; ,
&apos;Not In Range&apos;, &apos; Not In &apos; ,
&apos;Error&apos;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Calculated Operator</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Campaign_List_Generation__c</fullName>
        <label>Campaign List Generation</label>
        <referenceTo>Campaign_List_Generation__c</referenceTo>
        <relationshipLabel>Campaign List Generation Criteria</relationshipLabel>
        <relationshipName>Campaign_List_Generation_Criteria</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Field_API_Name__c</fullName>
        <label>Field API Name</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Field_Type__c</fullName>
        <label>Field Type</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Object__c</fullName>
        <label>Object</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Operator__c</fullName>
        <label>Operator</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Campaign List Generation Criteria</label>
    <nameField>
        <displayFormat>CR-{000000}</displayFormat>
        <label>Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Campaign List Generation Criteria</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/clsCampaignListSOQLGenerator.cls
global class clsCampaignListSOQLGenerator {
	public static string whereClause(string listId){
		Campaign_List_Generation__c clist = [select id,Transaction_Fields__c, campaign__c from Campaign_List_Generation__c where id = : listId];
		list<Campaign_List_Generation_Criteria__c> crList = [select id, Field_Type__c , Calculated_Operator__c, Object__c, Field_API_Name__c, Operator__c, Value__c, Calculated_Field_Type__c 
															 from Campaign_List_Generation_Criteria__c 
															 where Campaign_List_Generation__c = :  clist.id];
		list<String> whereClause = new List<String>();													 
		for (Campaign_List_Generation_Criteria__c c : crlist){ 
			string val = c.Value__c;
			if (c.Operator__c == 'Starts With'){
				val = val + '%';
			}else if (c.Operator__c == 'Contains' || c.Operator__c == 'Does Not Contain'){
				val = '%' + val + '%';
			}else if (c.Operator__c.contains ('In Range')){
				list<String> temp = val.split(','); 
				val = '';
				for (string s : temp){
					if (s != ''){
						if (c.Calculated_Field_Type__c == 'STRING'){ 
							val = val + '\'' + s + '\', ';
						}else{
							val = val + s + ', ';
						}
					}
				}
				if (val.length() > 0){
					val = val.substring(0, val.length()-2);
				}				
			}
			string fieldName = '';
			
			//if (clist.Transaction_Fields__c > 0 && c.Object__c =='Account'){
			//	fieldName = 'Account__r.' + c.Field_API_Name__c + ' '; 
			//}else{
				fieldName = c.Field_API_Name__c + ' ';
			//}
			if (c.Field_Type__c == 'REFERENCE'){
				fieldName = fieldname.replace('__c', '__r.name');	
			}
			if (c.Calculated_Field_Type__c == 'STRING'){
				if (c.Operator__c.contains ('In Range')){
					whereClause.add (fieldName + c.Calculated_Operator__c + '(' + val + ')');
				}else if(c.Operator__c.contains ('Does Not Contain')){
					whereClause.add ('( NOT ' + fieldName + c.Calculated_Operator__c + ' \'' + val + '\')');
				}else{
					whereClause.add(fieldName + c.Calculated_Operator__c + '\'' + val + '\'');
				}
			}else if (c.Calculated_Field_Type__c == 'DATE'){
				whereClause.add(fieldName + c.Calculated_Operator__c + val);
			}else if (c.Calculated_Field_Type__c == 'DATETIME'){
				//2012-04-13T00:00:00Z
				whereClause.add(fieldName + c.Calculated_Operator__c + val + 'T00:00:00Z');
			}else if (c.Calculated_Field_Type__c == 'NUMBER'){
				if (c.Operator__c.contains ( 'In Range')){
					whereClause.add (fieldName + c.Calculated_Operator__c + '(' + val + ')');
				}else{
					whereClause.add(fieldName + c.Calculated_Operator__c + val);
				}
			}else if (c.Calculated_Field_Type__c == 'BOOLEAN'){
				whereClause.add(fieldName + c.Calculated_Operator__c + val);
			}
		}
		string soql = '';
		for (string s : whereClause){
			soql = soql + s + ' and ' ;
		}
		if (soql != ''){
			soql = soql.substring(0, soql.length()-5);
		}
		
		return soql;
	}
}